mutation draftOrderUpdate($id: ID!, $input: DraftOrderInput!) {
  draftOrderUpdate(id: $id, input: $input) {
     draftOrder {
      id
      name
      email
      subtotalPrice
    lineItemsSubtotalPrice{
          presentmentMoney{
              amount
              currencyCode
          }
          shopMoney{
                amount
              currencyCode
          }
      }
      note2
      totalPrice
      lineItems(first: 100) {
          
          nodes {
              quantity
              variant{
                  id
                  price
                  availableForSale
                  title
              }
              product {
                  
                id
                 priceRangeV2{
                      maxVariantPrice{
                          amount
                          currencyCode
                      }
                  }
                title
                productType
                featuredImage {
                    url
                }
              }
          }
      }
    }
  }
}
