query getOrders($first: Int , $query: String){
  orders(first: $first,query: $query) {
    edges {
      node {
        id
        name
        phone
        createdAt
        displayFinancialStatus
        displayFulfillmentStatus
        returnStatus
        phone
      totalPriceSet{
          presentmentMoney{
              amount
              currencyCode
          }
          shopMoney{
              amount
              currencyCode
          }
      }
      billingAddress{
          address1
          firstName
          lastName
          city
          country
          zip
          phone
          id
      }
      }
    }
  }
}
